// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfIvhynw-zLCToEw4050c--NY5jE_dJOs',
    appId: '1:29617625388:ios:4525aa878cf6732044b489',
    messagingSenderId: '29617625388',
    projectId: 'vision-mate-c556a',
    storageBucket: 'vision-mate-c556a.firebasestorage.app',
    iosBundleId: 'com.example.visionmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfIvhynw-zLCToEw4050c--NY5jE_dJOs',
    appId: '1:29617625388:ios:4525aa878cf6732044b489',
    messagingSenderId: '29617625388',
    projectId: 'vision-mate-c556a',
    storageBucket: 'vision-mate-c556a.firebasestorage.app',
    iosBundleId: 'com.example.visionmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgzOhMSs5XfsEROtQGHtLbA6kgWWOW_EY',
    appId: '1:29617625388:web:7b700aa4bdeffea744b489',
    messagingSenderId: '29617625388',
    projectId: 'vision-mate-c556a',
    authDomain: 'vision-mate-c556a.firebaseapp.com',
    storageBucket: 'vision-mate-c556a.firebasestorage.app',
    measurementId: 'G-KJJKM26LJW',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgzOhMSs5XfsEROtQGHtLbA6kgWWOW_EY',
    appId: '1:29617625388:web:7b700aa4bdeffea744b489',
    messagingSenderId: '29617625388',
    projectId: 'vision-mate-c556a',
    authDomain: 'vision-mate-c556a.firebaseapp.com',
    storageBucket: 'vision-mate-c556a.firebasestorage.app',
    measurementId: 'G-KJJKM26LJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKIxVAsvLd6WT_I3oPddCFWxWDUnQTHCE',
    appId: '1:29617625388:android:3e73768e6797bf9a44b489',
    messagingSenderId: '29617625388',
    projectId: 'vision-mate-c556a',
    storageBucket: 'vision-mate-c556a.firebasestorage.app',
  );

}